/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/national/tools/{tool}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["setTool"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{code}/projects/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put: operations["update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{code}/projects/{slug}/resources/{resourceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateResource"];
        post?: never;
        delete: operations["detach"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{code}/projects/{slug}/members/{personId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["setRole"];
        post?: never;
        delete: operations["removeMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{code}/notion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_1"];
        put: operations["put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/national/sync/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/national/queue/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["decide"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/national/dead-letters/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["retry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{code}/sync/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["runDryRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{code}/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{code}/projects/{slug}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["status"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{code}/projects/{slug}/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["attach"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{code}/projects/{slug}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{code}/notion/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["check"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{code}/adoption/resources/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["people"];
        put?: never;
        post: operations["decide_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["status_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["roles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/national/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["tools"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/national/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["queue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/national/dead-letters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["deadLetters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["chapter"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{code}/terms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["terms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{code}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["sync"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{code}/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["resources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{code}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["members"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{code}/adoption": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["report"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/adoption/unmatched": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["unmatched"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ToolChange: {
            enabled: boolean;
            dryRun: boolean;
            reason: string | null;
        };
        LastRun: {
            status: string;
            mode: string;
            /** Format: date-time */
            ranAt: string;
            /** Format: int32 */
            applied: number;
            /** Format: int32 */
            removed: number;
            error: string | null;
        };
        ToolStatus: {
            tool: string;
            enabled: boolean;
            dryRun: boolean;
            writable: boolean;
            pauseReason: string | null;
            /** Format: int32 */
            maxRemovals: number;
            lastRun: components["schemas"]["LastRun"] | null;
        };
        ProjectInput: {
            name: string;
            slug: string | null;
            type: string | null;
            tags: string[];
            /** Format: uuid */
            termId: string | null;
            partner: string | null;
            /** Format: date */
            startsOn: string | null;
            /** Format: date */
            endsOn: string | null;
        };
        AccessPreview: {
            /** Format: int32 */
            people: number;
            /** Format: int32 */
            grants: number;
            /** Format: int32 */
            awaitingAgreement: number;
            asIfActive: boolean;
        };
        ActivityRow: {
            /** Format: date-time */
            at: string;
            actor: string | null;
            action: string;
            detail: string | null;
        };
        NotionPlan: {
            status: string;
            title: string;
            pageId: string | null;
            parentPageId: string | null;
            parentPath: string | null;
            matchedBy: string | null;
        };
        PlannedChange: {
            kind: string;
            tool: string;
            resource: string;
            person: string | null;
            accountId: string | null;
            fromAccess: string | null;
            toAccess: string | null;
        };
        ProjectDetail: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            status: string;
            type: string | null;
            tags: string[];
            /** Format: uuid */
            termId: string | null;
            term: string | null;
            partner: string | null;
            /** Format: date */
            startsOn: string | null;
            /** Format: date */
            endsOn: string | null;
            members: components["schemas"]["ProjectMemberRow"][];
            resources: components["schemas"]["ProjectResourceRow"][];
            /** Format: int32 */
            agreementsSigned: number;
            notion: components["schemas"]["NotionPlan"];
            preview: components["schemas"]["AccessPreview"];
            planned: components["schemas"]["PlannedChange"][];
            /** Format: date-time */
            lastDryRunAt: string | null;
            plannedOutOfDate: boolean;
            activity: components["schemas"]["ActivityRow"][];
            canEdit: boolean;
        };
        ProjectMemberRow: {
            /** Format: uuid */
            personId: string;
            name: string;
            email: string | null;
            status: string;
            /** Format: uuid */
            roleId: string | null;
            role: string | null;
            agreementStatus: string;
            lead: boolean;
        };
        ProjectResourceRow: {
            /** Format: uuid */
            resourceId: string;
            tool: string;
            name: string;
            state: string;
            audience: string;
            /** Format: uuid */
            roleId: string | null;
            role: string | null;
            access: string;
            requiresAgreement: boolean;
            tags: string[];
            sharedWith: string[];
            existsInTool: boolean;
            /** Format: int32 */
            getting: number;
            /** Format: int32 */
            awaitingAgreement: number;
        };
        ResourceInput: {
            /** Format: uuid */
            resourceId: string | null;
            tool: string | null;
            name: string | null;
            audience: string;
            /** Format: uuid */
            roleId: string | null;
            access: string;
            requiresAgreement: boolean;
            tags: string[];
        };
        MemberRoleInput: {
            /** Format: uuid */
            roleId: string | null;
        };
        NotionRouteInput: {
            kind: string;
            value: string;
            parent: string;
        };
        NotionSettingsInput: {
            teamspaceId: string | null;
            defaultParent: string | null;
            template: string | null;
            titlePattern: string;
            routes: components["schemas"]["NotionRouteInput"][];
        };
        NotionPageRef: {
            pageId: string;
            path: string | null;
            error: string | null;
            /** Format: date-time */
            checkedAt: string | null;
        };
        NotionRouteView: {
            kind: string;
            value: string;
            parent: components["schemas"]["NotionPageRef"];
        };
        NotionSettingsView: {
            configured: boolean;
            teamspaceId: string | null;
            defaultParent: components["schemas"]["NotionPageRef"] | null;
            template: components["schemas"]["NotionPageRef"] | null;
            titlePattern: string;
            routes: components["schemas"]["NotionRouteView"][];
            /** Format: int32 */
            problems: number;
            canEdit: boolean;
        };
        TaskDecision: {
            action: string;
            reason: string | null;
        };
        QueueTask: {
            /** Format: uuid */
            id: string;
            tool: string;
            action: string;
            description: string;
            /** Format: date-time */
            createdAt: string;
            status: string;
            doneBy: string | null;
            /** Format: date-time */
            doneAt: string | null;
        };
        DeadLetterRef: {
            /** Format: uuid */
            personId: string;
            /** Format: uuid */
            resourceId: string;
        };
        DeadLetter: {
            /** Format: uuid */
            personId: string;
            person: string;
            /** Format: uuid */
            resourceId: string;
            tool: string;
            resource: string;
            /** Format: int32 */
            attempts: number;
            lastError: string | null;
            /** Format: date-time */
            lastAttemptAt: string | null;
        };
        StatusChange: {
            status: string;
        };
        MemberInput: {
            /** Format: uuid */
            personId: string;
            /** Format: uuid */
            roleId: string | null;
        };
        AdoptionDecision: {
            action: string;
            target: string | null;
            /** Format: uuid */
            projectId: string | null;
        };
        AdoptionReport: {
            /** Format: date */
            grandfatheredUntil: string | null;
            scans: components["schemas"]["ScanStatus"][];
            resources: components["schemas"]["AdoptionResource"][];
            projects: components["schemas"]["ProjectOption"][];
            canEdit: boolean;
        };
        AdoptionResource: {
            /** Format: uuid */
            id: string;
            tool: string;
            name: string;
            state: string;
            target: string | null;
            /** Format: uuid */
            projectId: string | null;
            projectName: string | null;
            suggestedSlug: string | null;
            matchMethod: string | null;
            archived: boolean;
            gone: boolean;
            /** Format: date-time */
            snapshotAt: string | null;
            /** Format: int32 */
            expected: number;
            /** Format: int32 */
            grandfathered: number;
            /** Format: int32 */
            unknownAccounts: number;
            /** Format: int32 */
            wouldAdd: number | null;
        };
        ProjectOption: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            status: string;
        };
        ScanStatus: {
            tool: string;
            status: string;
            /** Format: date-time */
            ranAt: string;
            error: string | null;
            /** Format: int32 */
            resourcesFound: number;
            coversChapter: boolean;
        };
        StatusResponse: {
            service: string;
            version: string;
        };
        ProjectRoleOption: {
            /** Format: uuid */
            id: string;
            name: string;
            lead: boolean;
        };
        ChapterRef: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            role: string;
        };
        Me: {
            email: string;
            name: string | null;
            /** Format: uuid */
            personId: string | null;
            nationalAdmin: boolean;
            chapters: components["schemas"]["ChapterRef"][];
        };
        ChapterOverview: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            status: string;
            role: string;
            stats: components["schemas"]["ChapterStats"];
            registrationLink: string;
            /** Format: int32 */
            notionProblems: number;
        };
        ChapterStats: {
            /** Format: int32 */
            activeMembers: number;
            /** Format: int32 */
            alumni: number;
            /** Format: int32 */
            liveProjects: number;
            /** Format: int32 */
            leads: number;
        };
        TermOption: {
            /** Format: uuid */
            id: string;
            label: string;
        };
        ChapterSync: {
            tools: components["schemas"]["ToolSync"][];
            changes: components["schemas"]["PlannedChange"][];
        };
        ToolSync: {
            tool: string;
            status: string;
            mode: string;
            /** Format: date-time */
            ranAt: string;
            error: string | null;
            /** Format: int32 */
            adds: number;
            /** Format: int32 */
            changes: number;
            /** Format: int32 */
            removals: number;
            /** Format: int32 */
            drift: number;
            /** Format: int32 */
            unmatchedAccounts: number;
            /** Format: int32 */
            missingResources: number;
            /** Format: int32 */
            creates: number;
        };
        ChapterResourceOption: {
            /** Format: uuid */
            id: string;
            tool: string;
            name: string;
            state: string;
            projects: string[];
        };
        ProjectSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            status: string;
            type: string | null;
            tags: string[];
            term: string | null;
            partner: string | null;
            /** Format: int32 */
            members: number;
            /** Format: int32 */
            resources: number;
            /** Format: date-time */
            updatedAt: string;
        };
        AccountSummary: {
            tool: string;
            state: string;
        };
        MemberRow: {
            /** Format: uuid */
            personId: string;
            name: string;
            email: string | null;
            status: string;
            kind: string;
            chapterRole: string | null;
            title: string | null;
            projects: string[];
            accounts: components["schemas"]["AccountSummary"][];
            claimed: boolean;
        };
        AdoptionPerson: {
            /** Format: uuid */
            personId: string | null;
            name: string | null;
            login: string | null;
            verdict: string;
            matchedBy: string | null;
            access: string | null;
        };
        UnmatchedResource: {
            /** Format: uuid */
            id: string;
            tool: string;
            name: string;
            archived: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    setTool: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tool: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToolChange"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ToolStatus"][];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectDetail"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectDetail"];
                };
            };
        };
    };
    updateResource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
                slug: string;
                resourceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResourceInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectDetail"];
                };
            };
        };
    };
    detach: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
                slug: string;
                resourceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectDetail"];
                };
            };
        };
    };
    setRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
                slug: string;
                personId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberRoleInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectDetail"];
                };
            };
        };
    };
    removeMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
                slug: string;
                personId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectDetail"];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NotionSettingsView"];
                };
            };
        };
    };
    put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotionSettingsInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NotionSettingsView"];
                };
            };
        };
    };
    run: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    decide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskDecision"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["QueueTask"][];
                };
            };
        };
    };
    retry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DeadLetterRef"][];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DeadLetter"][];
                };
            };
        };
    };
    runDryRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectSummary"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectDetail"];
                };
            };
        };
    };
    status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusChange"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectDetail"];
                };
            };
        };
    };
    attach: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResourceInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectDetail"];
                };
            };
        };
    };
    addMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectDetail"];
                };
            };
        };
    };
    check: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NotionSettingsView"];
                };
            };
        };
    };
    people: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdoptionPerson"][];
                };
            };
        };
    };
    decide_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdoptionDecision"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdoptionReport"];
                };
            };
        };
    };
    status_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    roles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectRoleOption"][];
                };
            };
        };
    };
    tools: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ToolStatus"][];
                };
            };
        };
    };
    queue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["QueueTask"][];
                };
            };
        };
    };
    deadLetters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DeadLetter"][];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Me"];
                };
            };
        };
    };
    chapter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ChapterOverview"];
                };
            };
        };
    };
    terms: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TermOption"][];
                };
            };
        };
    };
    sync: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ChapterSync"];
                };
            };
        };
    };
    resources: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ChapterResourceOption"][];
                };
            };
        };
    };
    members: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MemberRow"][];
                };
            };
        };
    };
    report: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdoptionReport"];
                };
            };
        };
    };
    unmatched: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UnmatchedResource"][];
                };
            };
        };
    };
}
