/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/chapters/{code}/adoption/resources/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["people"];
        put?: never;
        post: operations["decide"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["chapter"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{code}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["sync"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{code}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["members"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{code}/adoption": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["report"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/adoption/unmatched": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["unmatched"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AdoptionDecision: {
            action: string;
            target: string | null;
            /** Format: uuid */
            projectId: string | null;
        };
        AdoptionReport: {
            /** Format: date */
            grandfatheredUntil: string | null;
            scans: components["schemas"]["ScanStatus"][];
            resources: components["schemas"]["AdoptionResource"][];
            projects: components["schemas"]["ProjectOption"][];
            canEdit: boolean;
        };
        AdoptionResource: {
            /** Format: uuid */
            id: string;
            tool: string;
            name: string;
            state: string;
            target: string | null;
            /** Format: uuid */
            projectId: string | null;
            projectName: string | null;
            suggestedSlug: string | null;
            matchMethod: string | null;
            archived: boolean;
            gone: boolean;
            /** Format: date-time */
            snapshotAt: string | null;
            /** Format: int32 */
            expected: number;
            /** Format: int32 */
            grandfathered: number;
            /** Format: int32 */
            unknownAccounts: number;
            /** Format: int32 */
            wouldAdd: number | null;
        };
        ProjectOption: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            status: string;
        };
        ScanStatus: {
            tool: string;
            status: string;
            /** Format: date-time */
            ranAt: string;
            error: string | null;
            /** Format: int32 */
            resourcesFound: number;
            coversChapter: boolean;
        };
        StatusResponse: {
            service: string;
            version: string;
        };
        ChapterRef: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            role: string;
        };
        Me: {
            email: string;
            name: string | null;
            /** Format: uuid */
            personId: string | null;
            nationalAdmin: boolean;
            chapters: components["schemas"]["ChapterRef"][];
        };
        ChapterOverview: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            status: string;
            role: string;
            stats: components["schemas"]["ChapterStats"];
            registrationLink: string;
        };
        ChapterStats: {
            /** Format: int32 */
            activeMembers: number;
            /** Format: int32 */
            alumni: number;
            /** Format: int32 */
            liveProjects: number;
            /** Format: int32 */
            leads: number;
        };
        ChapterSync: {
            tools: components["schemas"]["ToolSync"][];
            changes: components["schemas"]["PlannedChange"][];
        };
        PlannedChange: {
            kind: string;
            tool: string;
            resource: string;
            person: string | null;
            accountId: string | null;
            fromAccess: string | null;
            toAccess: string | null;
        };
        ToolSync: {
            tool: string;
            status: string;
            mode: string;
            /** Format: date-time */
            ranAt: string;
            error: string | null;
            /** Format: int32 */
            adds: number;
            /** Format: int32 */
            changes: number;
            /** Format: int32 */
            removals: number;
            /** Format: int32 */
            drift: number;
            /** Format: int32 */
            unmatchedAccounts: number;
            /** Format: int32 */
            missingResources: number;
        };
        AccountSummary: {
            tool: string;
            state: string;
        };
        MemberRow: {
            /** Format: uuid */
            personId: string;
            name: string;
            email: string | null;
            status: string;
            kind: string;
            chapterRole: string | null;
            title: string | null;
            projects: string[];
            accounts: components["schemas"]["AccountSummary"][];
            claimed: boolean;
        };
        AdoptionPerson: {
            /** Format: uuid */
            personId: string | null;
            name: string | null;
            login: string | null;
            verdict: string;
            matchedBy: string | null;
            access: string | null;
        };
        UnmatchedResource: {
            /** Format: uuid */
            id: string;
            tool: string;
            name: string;
            archived: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    people: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdoptionPerson"][];
                };
            };
        };
    };
    decide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdoptionDecision"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdoptionReport"];
                };
            };
        };
    };
    status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Me"];
                };
            };
        };
    };
    chapter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ChapterOverview"];
                };
            };
        };
    };
    sync: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ChapterSync"];
                };
            };
        };
    };
    members: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MemberRow"][];
                };
            };
        };
    };
    report: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdoptionReport"];
                };
            };
        };
    };
    unmatched: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UnmatchedResource"][];
                };
            };
        };
    };
}
